### ISSUE TITLE
Multiplication of mu is missing in the term2 (sum_2)

### ISSUE THREAD

**Issue by tonygracious** [fraspass/meg#1]
https://github.com/fraspass/meg/blob/03650bd2e32487e4c50a9afe9b3e2e9848290b4b/lib/meg/meg.py#L1214

The derivative of likelihood with phi  has a  multiplicative term of mu for sum_2.

**Comment by fraspass** [comment]
Many thanks for spotting this! It has been fixed for `vals_phi` and `vals_phi_prime`.
